# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-12 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('release_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DataSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=64)),
                ('search_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=16)),
                ('data_search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicsearch.DataSearch')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('track_link', models.CharField(max_length=128)),
                ('length', models.DurationField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicsearch.Album')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicsearch.Artist')),
                ('search_result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicsearch.SearchResult')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicsearch.Artist'),
        ),
    ]
