# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-25 13:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasearch',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasearch',
            name='search_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 25, 13, 47, 10, 621399)),
        ),
    ]
