# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-25 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsearch', '0002_auto_20181025_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasearch',
            name='search_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 25, 18, 18, 51, 28663)),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
