# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-24 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsearch', '0002_auto_20181024_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='datasearch',
            name='keyword',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='datasearch',
            name='search_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 24, 12, 7, 28, 16294)),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
