# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-24 21:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsearch', '0007_auto_20181024_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasearch',
            name='search_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 24, 21, 30, 45, 2837)),
        ),
    ]
