# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-24 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicsearch', '0009_auto_20181024_2134'),
    ]

    operations = [
    ]
